import type { Metadata } from "next";
import { Roboto_Flex, Rubik, Quicksand } from "next/font/google";
import "./globals.css";

const robotoFlex = Roboto_Flex({
  variable: "--font-roboto-flex",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SettingsProvider } from "@/context/settings-context";
import { TimerProvider } from "@/context/timer-context";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} antialiased`}
      >
        <SettingsProvider>
          <TimerProvider>
            {children}
          </TimerProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
